# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Base_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import numpy as np
import binaryfile_read_write as wrb
import open3ds as op
import filops as fp
import read_java_bin
import MouseConnect as ms
from PyQt5 import QtCore, QtGui, QtWidgets
import MouseConnect as mouse
from PyQt5.QtWidgets import QDialog, QApplication, QColorDialog, QLineEdit, QAction
from PyQt5.QtGui import QColor
from PyQt5.QtWidgets import QShortcut
from PyQt5.QtGui import QKeySequence
from PyQt5.QtWidgets import QFileDialog
# from GUI2 import Ui_Form
import pandas as pg
from pyqtgraph import PlotWidget, plot
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import Qt
from PyQt5 import QtCore, QtGui, QtWidgets
import UFiedlCalculation
# from GUI4 import Ui_Form_bragg, Ui_Form_impurity, Ui_Form_Cut, Ui_Form_linecut
import filops as fp
from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from PyQt5.QtWidgets import QShortcut
from PyQt5.QtGui import QKeySequence
from PyQt5.QtWidgets import QMainWindow
import fieldops
import javabin
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from subtract_fit import *
import matplotlib.pyplot as plt
from contrast_ratio import Ui_Form_contrast
from PyQt5.QtWidgets import QApplication
from self_color_list import colorlistfunction
from matplotlib.colors import  LinearSegmentedColormap
class Baseui(QMainWindow):
    def __init__(self):
        QMainWindow.__init__(self)
        #QWidget.__init__(self)
        self.Newbinpath = r'C:\data'
        self.setObjectName("Form")
        self.resize(874, 726)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName('centerwidget')

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.color_count = 0
        self.counts = 0

        self.colorlist,self.lenss,self.cnamelist= colorlistfunction()
        self.nbins =100000


        self.cmaplist = ['YlOrBr','YlOrBr_r','Blues','Blues_r','binary_r','binary',
                         'autumn','autumn_r','YlOrRd','YlOrRd_r','Reds','Reds',
                         'Purples','Purples_r','copper','copper_r','OrRd','OrRd_r','RdBu',
                         'RdBu_r','coolwarm','coolwarm_r']
        self.cmap = self.cmaplist[self.color_count]

        self.heighsss =1
        self.width = 8
        self.height = 8
        self.dpi = 100

        #self.cm = LinearSegmentedColormap.from_list(self.names+str(1),self.colorlist[self.names+str(1)],N =self.nbins)
        self.figure = Figure(figsize=(self.width, self.height), dpi=self.dpi)
        self.canvas = FigureCanvas(self.figure)
        self.ax = self.figure.add_subplot(111)
        self.ax.axis('off')

        self.canvas.draw()
        self.horizontalLayout.addWidget(self.canvas)

        self.setCentralWidget(self.centralwidget)


        self.shortcut = QShortcut(QKeySequence('F3'),self.centralwidget,self.changecolor)
        self.shortcut_1 = QShortcut(QKeySequence('Ctrl+Q'),self.centralwidget,self.dialog_open)
        self.shortcut_2 = QShortcut(QKeySequence('Ctrl+S'),self.centralwidget,self.savepng)
        self.shortcut_3 = QShortcut(QKeySequence('Ctrl+B'),self.centralwidget,self.savedata_bin)
        self.shortcut_4 = QShortcut(QKeySequence('F11'),self.centralwidget,self.contrast_ratio)
        self.shortclipboard = QShortcut(QKeySequence('Ctrl+C'),self.centralwidget,self.to_clipboard)
        self.shortcut_color_decrease = QShortcut(QKeySequence('F2'),self.centralwidget,self.changecolor_decrease)


    def changecolor(self):
        self.color_count = self.color_count + 1
        time = int(self.color_count%(len(self.cmaplist)+self.lenss))

        print(time)
        if time <self.lenss:
            self.cmap = LinearSegmentedColormap.from_list(self.cnamelist[time],self.colorlist[self.cnamelist[time]],N =self.nbins)
            print(self.cnamelist[time])
        else:
            self.cmap = self.cmaplist[time-self.lenss]
            print(self.cmap)
        self.topomap_draw(self.topo)

    def changecolor_decrease(self):
        self.color_count = self.color_count -1
        time = np.abs(int(self.color_count%(len(self.cmaplist)+self.lenss)))

        if time <self.lenss:
            self.cmap = LinearSegmentedColormap.from_list(self.cnamelist[time],self.colorlist[self.cnamelist[time]],N =self.nbins)
        else:
            self.cmap = self.cmaplist[time-self.lenss]
        self.topomap_draw(self.topo)


    def dialog_open(self):
        self.topo = dialog_function(self.centralwidget,self.topo)
        self.topomap_draw(self.topo)


    def to_clipboard(self):
        """
        将图片复制到剪贴板上
        :return:
        """
        self.ax.axis('off')
        QApplication.clipboard().setImage(QWidget.grab(self.figure.canvas).toImage())
        self.ax.axis('on')
    def savepng(self):
        """
        保存图片为eps/png
        :return:
        """

        self.counts = self.counts + 1
        self.ax.axis('off')
        self.figure = Figure(figsize=(10,10),dpi=100)
        self.figure.savefig(self.Newbinpath+'\\'+'topo'+'_'+str(self.counts)+'.eps',dpi=600,format='eps')
        self.figure.savefig(self.Newbinpath+'\\'+'topo'+'_'+str(self.counts)+'.png',dpi=600,format='png')
        self.ax.axis('on')


    def savedata_bin(self):
        """
        self.count_bin = self.count_bin+1
        path = self.Newbinpath +'\\'
        """
        #功能暂时缺失

    def contrast_ratio(self):
        self.max = np.max(self.topo)
        self.min = np.min(self.topo)
        self.median = np.median(self.topo)
        self.windows = Ui_Form_contrast()
        self.windows.slider_emit.connect(self.sliderfunction)
        # self.windows.slider_2_emit.connect(self.slidernumber2)
        self.windows.show()


    def sliderfunction(self,number1,number2):
        self.topomap_draw(self.topo,number1/10,number2/10)


    def topomap_draw(self,data,vmin=0,vmax=100):
        print(vmin,vmax)
        self.vmin = np.percentile(data,vmin)
        self.vmax = np.percentile(data,vmax)
        self.ax.clear()
        self.ax.axis('off')
        self.ax.pcolormesh(data, vmin=self.vmin, vmax=self.vmax, cmap=self.cmap)

        self.canvas.draw()



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)

    ui = Baseui()
    ui.show()
    sys.exit(app.exec_())
