# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Base_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import numpy as np
import binaryfile_read_write as wrb
import open3ds as op
import filops as fp
import read_java_bin
import MouseConnect as ms
from PyQt5 import QtCore, QtGui, QtWidgets
import MouseConnect as mouse
from PyQt5.QtWidgets import QDialog, QApplication, QColorDialog,QLineEdit,QAction
from PyQt5.QtGui import QColor
from PyQt5.QtWidgets import QShortcut
from PyQt5.QtGui import  QKeySequence
from PyQt5.QtWidgets import QFileDialog
#from GUI2 import Ui_Form
import pandas as pg
from pyqtgraph import PlotWidget, plot
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import Qt
from PyQt5 import QtCore, QtGui, QtWidgets
import UFiedlCalculation
#from GUI4 import Ui_Form_bragg, Ui_Form_impurity, Ui_Form_Cut, Ui_Form_linecut
import filops as fp
from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from PyQt5.QtWidgets import QShortcut
from PyQt5.QtGui import QKeySequence
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from subtract_fit import *
import matplotlib.pyplot as plt
from contrast_ratio import Ui_Form_contrast
from GUI_Test import Ui_MainWindow
class Baseui(QMainWindow,Ui_MainWindow):
    def __init__(self,):
        super(Baseui, self).__init__()
        self.Newbinpath = r'C:\data'
        self.setObjectName("Form")
        self.resize(874, 726)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName('centerwidget')

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cmap = 'binary'
        self.counts = 0
        self.color_count = 0
        self.width = 8
        self.topo = np.zeros((200,200))
        for i in range(200):
            for j in range(200):
                self.topo[i][j] = i*2+j
        self.height = 8
        self.dpi = 100
        self.figure = Figure(figsize=(self.width, self.height), dpi=self.dpi)
        self.canvas = FigureCanvas(self.figure)
        self.ax = self.figure.add_subplot(111)
        self.ax.pcolormesh(self.topo)
        self.canvas.draw()
        #self.retranslateUi(self)
        
        self.horizontalLayout.addWidget(self.canvas)

        self.cmaplist = ['YlOrBr','YlOrBr_r','Blues','Blues_r','binary_r','binary',
                         'autumn','autumn_r','YlOrRd','YlOrRd_r','Reds','Reds',
                         'Purples','Purples_r','copper','copper_r','OrRd','OrRd_r','RdBu',
                         'RdBu_r','coolwarm','coolwarm_r']
        self.shortcut = QShortcut(QKeySequence('F3'),self.centralwidget,self.changecolor)
        self.shortcut_1 = QShortcut(QKeySequence('Ctrl+Q'),self.centralwidget,self.dialog_open)
        self.shortcut_2 = QShortcut(QKeySequence('Ctrl+S'),self.centralwidget,self.savepng)
        self.shortcut_3 = QShortcut(QKeySequence('Ctrl+B'),self.centralwidget,self.savedata_bin)
        self.shortcut_4 = QShortcut(QKeySequence('F11'),self.centralwidget,self.contrast_ratio)
        self.setCentralWidget(self.centralwidget)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Baseui()
    ui.show()
    sys.exit(app.exec_())
