# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contrast_ratio.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from typing import Union

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal

class Ui_Form_contrast(QtWidgets.QWidget):
    slider_emit = pyqtSignal(int,int)
    def __init__(self):
        super(Ui_Form_contrast, self).__init__()
        self.setObjectName("Form")
        self.resize(373, 85)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setObjectName("label")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.splitter)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        self.label_2.setObjectName("label_2")
        self.horizontalSlider = QtWidgets.QSlider(self.splitter)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.splitter)

        self.horizontalSlider_2.setMaximum(500)
        self.horizontalSlider_2.setMinimum(0)
        self.horizontalSlider.setMaximum(1000)
        self.horizontalSlider.setMinimum(500)
        self.horizontalSlider.setValue(1000)

        self.retranslateUi(self)

        self.horizontalSlider.valueChanged.connect(self.slider1)
        self.horizontalSlider_2.valueChanged.connect(self.slider1)
        QtCore.QMetaObject.connectSlotsByName(self)


    def slider1(self):
        value = self.horizontalSlider.value()
        value2 = self.horizontalSlider_2.value()
        self.slider_emit.emit(value2,value)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "百分之0到百分之50"))
        self.label_2.setText(_translate("Form", "百分之50到百分之100"))

class Ui_Form_Contrast_single(QtWidgets.QWidget):
    slider_emit = pyqtSignal(int)
    def __init__(self):
        super(Ui_Form_Contrast_single, self).__init__()
        self.setObjectName("Form")
        self.resize(411, 97)
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.splitter)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.verticalLayout.addWidget(self.splitter)
        self.horizontalScrollBar.setMaximum(10000)
        self.horizontalScrollBar.setMinimum(0)
        self.horizontalScrollBar.setValue(0)
        self.retranslateUi()
        self.horizontalScrollBar.valueChanged.connect(self.slider1)
        QtCore.QMetaObject.connectSlotsByName(self)

    def slider1(self):
        value = self.horizontalScrollBar.value()
        self.slider_emit.emit(value)
    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "偏离量设置(0~1000)"))
