# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI1.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import numpy as np
import binaryfile_read_write as wrb
import open3ds as op
import MouseConnect as ms
from PyQt5 import QtCore, QtGui, QtWidgets
import MouseConnect as mouse
from PyQt5.QtWidgets import QDialog,QApplication,QColorDialog
from PyQt5.QtGui import QColor
from PyQt5.QtWidgets import QFileDialog
from GUI2 import Ui_Form
import pandas as pg
from pyqtgraph import PlotWidget, plot
from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5 import QtCore, QtGui, QtWidgets
#from GUI3 import Ui_Form
class Ui_Form(object):
    def setupUi(self, Form,data):
        Form.setObjectName("Form")
        Form.resize(874, 726)
        self.data =data
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        width_s = self.graphicsView.width()
        height_s =self.graphicsView.height()
        dpi = self.graphicsView.physicalDpiX()
        m = ms.Plotcanvas(self.graphicsView, width=15, height=15,topo=self.data)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 709)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 20))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("drift_correction")

        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionchoose_color = QtWidgets.QAction(MainWindow)
        self.actionchoose_color.setObjectName("actionchoose_color")


        self.actionopen3ds = QtWidgets.QAction(MainWindow)
        self.actionopen3ds.setObjectName("actionopen3ds")
        self.actionopenbin = QtWidgets.QAction(MainWindow)
        self.actionopenbin.setObjectName("actionopenbin")


        self.actionochooseimpurities=QtWidgets.QAction(MainWindow)
        self.actionochooseimpurities.setObjectName("choose_impurities")
        self.actionoaddmask=QtWidgets.QAction(MainWindow)
        self.actionoaddmask.setObjectName("add_mask")

        self.actionochooseBraggPeak = QtWidgets.QAction(MainWindow)
        self.actionochooseBraggPeak.setObjectName("chooseBraggPeak")


        self.menu.addAction(self.actionopen3ds)
        self.menu.addAction(self.actionopenbin)
        self.menu_2.addAction(self.actionchoose_color)
        self.menu_3.addAction(self.actionochooseimpurities)
        self.menu_3.addAction(self.actionoaddmask)
        self.menu_4.addAction(self.actionochooseBraggPeak)


        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        self.actionchoose_color.triggered.connect(self.choosecolor)
        self.actionopen3ds.triggered.connect(self.open3ds_or_sxm)
        self.actionopenbin.triggered.connect(self.openbinfile)
        self.actionochooseimpurities.triggered.connect(self.openUI_Windows)
        self.actionochooseBraggPeak.triggered.connect(self.openUI_Windows)


        self.windows = QtWidgets.QWidget

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def choosecolor(self):
        self.color = QColorDialog.getColor()


    def open3ds_or_sxm(self):
        self.filename,_ = QFileDialog.getOpenFileName()
        self.Newpath=op.openup(self.filename)
        print(self.Newpath)

    def choose_peak(self):
        self.fftdata = np.fft.fft2(self.topo)
        self.fftdata = np.log10(np.abs(self.fftdata)**2)
        self.windows =QtWidgets.QWidget()
        self.ui = Ui_Form()
        self.ui.setupUi(self.windows,self.topo)
        self.windows.show()

    def openbinfile(self):
        self.filename,_ =QFileDialog.getOpenFileName(filter='(*.bin)')
        self.topo,= wrb.read_java_bin_single_layer(self.filename)
        self.cmap ='binary'
        self.m = ms.Plotcanvas(self.graphicsView, width=10, height=10,topo=self.topo)


    def openUI_Windows(self):
        self.windows =QtWidgets.QWidget()
        self.ui = Ui_Form()
        self.ui.setupUi(self.windows,self.topo)
        self.windows.show()
    def keyPressEvent(self,event):
        key = event.key()
        print("nihao")


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "打开文件"))
        self.menu_2.setTitle(_translate("MainWindow", "调节颜色"))
        self.menu_3.setTitle(_translate("MainWindow", "相位敏感QPI"))
        self.menu_4.setTitle(_translate("MainWindow", "drift_correction"))
        self.actionchoose_color.setText(_translate("MainWindow", "choose color"))
        self.actionopen3ds.setText(_translate("MainWindow", "open3ds"))
        self.actionopenbin.setText(_translate("MainWindow", "openbin"))
        self.actionochooseimpurities.setText(_translate("MainWindow","choose_impurities"))
        self.actionoaddmask.setText(_translate("MainWindow","addmask"))
        self.actionochooseBraggPeak.setText(_translate("MainWindow","chooseBraggPeak"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
