# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI3.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import MouseConnect as ms


class Ui_Form(object):
    def setupUi(self, otherWindow,topo ):

        otherWindow.setObjectName("otherWindow")
        otherWindow.resize(800, 600)
        self.topo = topo
        self.centralwidget = QtWidgets.QWidget(otherWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget )
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        otherWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(otherWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        otherWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(otherWindow)
        self.statusbar.setObjectName("statusbar")
        otherWindow.setStatusBar(self.statusbar)
        m = ms.Plotcanvas(self.graphicsView, width=20, height=20,topo=self.topo)

        self.retranslateUi(otherWindow)
        QtCore.QMetaObject.connectSlotsByName(otherWindow)

    def retranslateUi(self, otherWindow):
        _translate = QtCore.QCoreApplication.translate
        otherWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Form()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
